### ISSUE TITLE
Generate HTML file for WebRTI and execute webGLRTIMaker.exe

### ISSUE THREAD

**Issue by thanneken** [CenterForDigitalHumanities/SpectralRTI_Toolkit#29]
or add the webGLRTIMaker command to the deferred batch command file

**Comment by thehabes** [comment]
I did not correctly call out to the webRTI maker, in fact I think it tried to call the fitter again, so that's no good. Working through this flow, I see that an RTI process must be selected because the runFitter() function to create an RTI checks whether or not WebRTI is desired and if so, the fitter will pass the RTI file off to the WebRTI maker.

These means a couple things for UI
1.  WebRTI as a lone choice is not valid, the program doesn't do anything.  In code, that means `if(!(acRakingDesired || acRtiDesired || xsRtiDesired || xsRakingDesired || psRtiDesired || psRakingDesired || csRtiDesired || csRakingDesired))`, tell the user theres nothing to do.  Perhaps this should be denoted in the UI Window somehow (like asterisk or a different color for the labels next to the checkbox).

2.  If an RTI process is not selected, the WebRTI process should not be able to be selected.

3. A workflow of "provide me an existing RTI file to make a WebRTI file out of it" is very possible, which may be of use to a set of users.  

I will fix it to work as is, but I will keep a thought to these points as I do it.

**Comment by thehabes** [comment]
I do believe  we are going to take a little extra time with this so 3. is possible.

**Comment by thehabes** [comment]
This has been implemented.  In general, this process is working but needs a UI review.
